### ISSUE TITLE
Inconsistent go vendoring since 2.10.30

### ISSUE THREAD

**Issue by johanneskastl** [ansible-semaphore/semaphore#2501]
HI all,

I am packaging semaphore for openSUSE. Unfortunately, since 2.10.30 the vendoring is inconsistent, the builds break. Unfortunately vendoring is necessary, as the builds are done in an offline environment.

I tried with 2.10.32, but the issue persists.

Could you have a look at this?

Kind Regards,
Johannes

```
[   15s] + go build -mod=vendor -buildmode=pie '-ldflags=    -X github.com/ansible-semaphore/semaphore/util.Ver=2.10.32    -X github.com/ansible-semaphore/semaphore/util.Commit=f33944e0    -X github.com/ansible-semaphore/semaphore/util.Date=2024-10-22T08:02:45Z' -o bin/ansible-semaphore ./cli/main.go
[   15s] go: inconsistent vendoring in /home/abuild/rpmbuild/BUILD/ansible-semaphore-2.10.32:
[   15s] 	github.com/Masterminds/squirrel@v1.5.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/coreos/go-oidc/v3@v3.9.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/creack/pty@v1.1.23: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-git/go-git/v5@v5.11.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-gorp/gorp/v3@v3.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-ldap/ldap/v3@v3.4.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-sql-driver/mysql@v1.7.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/golang-jwt/jwt/v4@v4.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/google/go-github@v17.0.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/gorilla/context@v1.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/gorilla/handlers@v1.5.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/gorilla/mux@v1.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/gorilla/securecookie@v1.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/gorilla/websocket@v1.5.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/lib/pq@v1.10.9: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/robfig/cron/v3@v3.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/sirupsen/logrus@v1.9.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/snikch/goodman@v0.0.0-20171125024755-10e37e294daa: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/spf13/cobra@v1.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/thedevsaddam/gojsonq/v2@v2.5.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	go.etcd.io/bbolt@v1.3.9: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/crypto@v0.21.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/oauth2@v0.17.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	dario.cat/mergo@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/Azure/go-ntlmssp@v0.0.0-20221128193559-754e69321358: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/Microsoft/go-winio@v0.6.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/ProtonMail/go-crypto@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/cloudflare/circl@v1.3.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/cyphar/filepath-securejoin@v0.2.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/emirpasic/gods@v1.18.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/felixge/httpsnoop@v1.0.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-asn1-ber/asn1-ber@v1.5.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-git/gcfg@v1.5.1-0.20230307220236-3a3c6141e376: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-git/go-billy/v5@v5.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/go-jose/go-jose/v3@v3.0.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/golang/protobuf@v1.5.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/google/go-querystring@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/google/uuid@v1.6.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/inconshreveable/mousetrap@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/jbenet/go-context@v0.0.0-20150711004518-d14ea06fba99: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/kevinburke/ssh_config@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/lann/builder@v0.0.0-20180802200727-47ae307949d0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/lann/ps@v0.0.0-20150810152359-62de8c46ede0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/pjbgf/sha1cd@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/rogpeppe/go-internal@v1.12.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/sergi/go-diff@v1.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/skeema/knownhosts@v1.2.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/spf13/pflag@v1.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	github.com/xanzy/ssh-agent@v0.3.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/mod@v0.15.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/net@v0.23.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/sys@v0.18.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	golang.org/x/tools@v0.18.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	google.golang.org/appengine@v1.6.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	google.golang.org/protobuf@v1.33.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 	gopkg.in/warnings.v0@v0.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
[   15s] 
[   15s] 	To ignore the vendor directory, use -mod=readonly or -mod=mod.
[   15s] 	To sync the vendor directory, run:
[   15s] 		go mod vendor
[   15s] error: Bad exit status from /var/tmp/rpm-tmp.D2evNA (%build)
```

**Comment by johanneskastl** [comment]
This is still an issue with 2.10.42. Could someone have a look, please?

**Comment by fiftin** [comment]
@johanneskastl Semaphore repository doesn't have vendor directory. So, it can be your local copy issue. I never used `vendor` but looks like you should remove your current `vendor` directory.

**Comment by johanneskastl** [comment]
This is a problem caused by the go.mod and/or go.sum files. Normally (in the other packages where I encountered such a problem) a `go mod tidy` fixes issues like this.

Unless you are trying to build offline this does not show, unfortunately...

**Comment by fiftin** [comment]
@johanneskastl

you can call `go mod vendor` before `go build -mod=vendor...`. I don't see reason to add vendor directory to the repository.

**Comment by johanneskastl** [comment]
Sorry, you did misunderstand me. There is no need to add a vendor directory. What I am doing is calling `go mod vendor` before building.

But as this creates the vendor directory based on the `go.mod` and `go.sum` files, it fails, if those files contain inconsistent vendoring instructions.

Hence this is something that should be fixed in the repository, by running `go mod tidy`.

I hope I could explain it better now?

**Comment by fiftin** [comment]
@johanneskastl you can try `develop` branch.

**Comment by kastl-ars** [comment]
Unfortunately this is still broken, even in 2.11.3.

I have no idea how the release process is under the hood, but I would highly recommend and appreciate if `go mod tidy` could be included in there before each release...

**Comment by fiftin** [comment]
Hi @kastl-ars I did. Can you test `develop` branch?

**Comment by fiftin** [comment]
@kastl-ars are you use tags to get required version of source code?

**Comment by fiftin** [comment]
I don't know how to automate `go mod tidy` because it need a commit. Let me know if you have idea.

**Comment by kastl-ars** [comment]
> [@kastl-ars](https://github.com/kastl-ars) are you use tags to get required version of source code?

Yes, we do. I'll try to test the develop branch later today.

**Comment by johanneskastl** [comment]
I am not sure why, but with one of the latest upgrades this seems to be solved. I have a hunch that this might have been completely unrelated. I'll close this for now and reopen, if it reappears.

Thanks for your help!
